services:
  adonis_app:
    container_name: box-organizer-be
    image: gian518/box-organizer
    restart: unless-stopped
    build:
      context: .
      target: dependencies
    ports:
      - 3003:3003
      - 9229:9229
    environment:
      - PORT=3003
      - APP_KEY=sXvwOfUoQKo-QeoqsC2krddOciT8Vs2h
      - DRIVE_DISK=local
      - DB_CONNECTION=sqlite
      - DOMAIN=yourdomain.com
    volumes:
      - box-organizer-be:/home/node/app
      # Uncomment the below line if you developing on MacOS
      # - /home/node/app/node_modules

volumes:
  box-organizer-be: